'use strict';

var assert = require('assert');
var gutil = require('gulp-util');
var snakeparser = require('./');

describe('gulp-snakeparser', function() {
	it('should generate a parser', function(done) {
		var stream = snakeparser();

		stream.write(new gutil.File({
			base: __dirname,
			path: __dirname + '/tmp/file.sg',
			contents: new Buffer('start = +("a" | "b")')
		}));

		stream.once('data', function(file) {
			assert(file.isBuffer());
			assert.equal(file.path, __dirname + '/tmp/file.js');
			assert.equal(file.relative, 'tmp/file.js');
			assert(/Generated by snake parser/.test(file.contents.toString()));
			assert(/^module.exports = /.test(file.contents.toString()));
			done();
		});
	});

	it('should set the function to "parse"', function(done) {
		var stream = snakeparser({exportVariable: 'parse'});

		stream.write(new gutil.File({
			base: __dirname,
			path: __dirname + '/tmp/file.sg',
			contents: new Buffer('start = +("a" | "b")')
		}));

		stream.once('data', function(file) {
			assert(/^parse = /.test(file.contents.toString()));
			done();
		});
	});
});